### ISSUE TITLE
Add a context to frames

### ISSUE THREAD

**Issue by Th3Mouk** [TailorDev/Watson#27] opened 2015-10-07 07:18 UTC
The aim is to propose the management of multiple context of work. For example `watson start sonata +formatter --context=home`, `watson start sonata +formatter --context=office` 

The report could have this format:

Total time: 41s

Total home: 18s
125daea  23:13 to 23:14         18s  sonata  [formatter]

Total office: 23s
125daeb  23:14 to 23:15         23s  sonata  [formatter]

**Comment by jmaupetit** [comment] 2015-10-07 07:25
Why don't you use a `+home` or `+office` tag for that?

**Comment by Th3Mouk** [comment] 2015-10-07 07:39
Cause the report has this format : 
```sh
Wed 30 September 2015 -> Wed 07 October 2015

sonata - 14s
	[formatter         07s]
	[home              07s]
	[office            14s]

ssu - 43s
	[questionnaire         18s]
	[home              10s]
	[office            08s]

cga - 12s
	[contact         12s]
	[home              06s]
	[office            16s]
```

And is less efficient for extract data, compare to 

```sh

Total: xx:xx:xx

Total office: xx:xx:xx

14s sonata [formatter]
08s ssu [contact]
16s cga [questionnaire]

Total home: xx:xx:xx

07s sonata [formatter]
10s ssu [contact]
06s cga [questionnaire]
```

It's a proposition i don't have the background of the project and i can't estimate quantity of work needed.

**Comment by jmaupetit** [comment] 2015-10-07 13:55
So the problem is that the `report` command is project-centric. What about adding a tag-centric option to this command?
Ping @k4nar

**Comment by k4nar** [comment] 2015-10-12 13:24
@Th3Mouk : With your example, you can get something very similar to the second output by running `watson report -T office` and then `watson report -T home`.

I really think that tags should be the only way to add context to a frame. But I'm sure there are plenty of ways to improve the report command.

**Comment by SpotlightKid** [comment] 2015-10-17 21:39
The [todo.txt spec](https://github.com/ginatrapani/todo.txt-cli/wiki/The-Todo.txt-Format) uses the ampersand to denote context, e.g. `@home` or `@office`. Maybe watson could allow `@context` as an alternative syntax for `+@context` when starting a frame?

**Comment by jmaupetit** [comment] 2016-09-30 16:36
I think proper usage of tags should be sufficient for this. I'll close this.

**Closed by jmaupetit** 2016-09-30 16:36 UTC
Labels: question
