### ISSUE TITLE
Allow late start on a task

### ISSUE THREAD

**Issue by raphaelfournier** [TailorDev/Watson#223] opened 2018-09-11 15:17 UTC
I regularly start a task and realize several minutes later that I forgot to start watson. I would really like an option to the `start` command like this `watson start project +foobar -d 5m` which would add 5 minutes to the start date of my task (d is for `delay`). It could be more precise or with a different format (like: `-d 04:45` to add 4 minutes and 45 seconds`), I am not fixed on that.

I may implement that in the future, but if someone wants to do it first, be my guest :-)

**Comment by jmaupetit** [comment] 2018-09-11 15:42
Hi @raphaelfournier! Thanks for the report. I'm closing this as a duplicate of #75. Ping me if I'm wrong. Definitely, this is something users need.

**Closed by jmaupetit** 2018-09-11 15:42 UTC
Labels: duplicate, feature request
