### ISSUE TITLE
watson not launching 

### ISSUE THREAD

**Issue by Niedzwiedzw** [TailorDev/Watson#439] opened 2021-06-21 07:51 UTC
❯ watson status
Traceback (most recent call last):
  File "/home/niedzwiedz/.local/bin/watson", line 5, in <module>
    from watson.__main__ import cli
  File "/home/niedzwiedz/.local/lib/python3.9/site-packages/watson/__main__.py", line 2, in <module>
    from watson import cli
  File "/home/niedzwiedz/.local/lib/python3.9/site-packages/watson/cli.py", line 515, in <module>
    def report(watson, current, from_, to, projects, tags, ignore_projects,
  File "/usr/lib/python3.9/site-packages/click/decorators.py", line 247, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/home/niedzwiedz/.local/lib/python3.9/site-packages/watson/cli.py", line 48, in __init__
    super(MutuallyExclusiveOption, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2482, in __init__
    super().__init__(param_decls, type=type, multiple=multiple, **attrs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 2108, in __init__
    raise ValueError(
ValueError: 'default' must be a list when 'multiple' is true.

**Comment by Niedzwiedzw** [comment] 2021-06-21 08:12
reverting to older version of `click` worked
(pip install click==7.1.1)

**Comment by jmaupetit** [comment] 2021-06-21 08:14
Closing as duplicate of #430

**Closed by jmaupetit** 2021-06-21 08:14 UTC
Labels: duplicate
