### ISSUE TITLE
watson broken after python-arrow upgrade

### ISSUE THREAD

**Issue by szigetva** [TailorDev/Watson#414] opened 2021-03-19 08:37 UTC
`$ watson log`
`Traceback (most recent call last):`
`  File "/usr/bin/watson", line 33, in <module>
    sys.exit(load_entry_point('td-watson==1.10.0', 'console_scripts', 'watson')())`
`  File "/usr/bin/watson", line 25, in importlib_load_entry_point
    return next(matches).load()`
`  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))`
`  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)`
`  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import`
`  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load`
`  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked`
`  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked`
`  File "<frozen importlib._bootstrap_external>", line 790, in exec_module`
`  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed`
`  File "/usr/lib/python3.9/site-packages/watson/__main__.py", line 2, in <module>
    from watson import cli`
`  File "/usr/lib/python3.9/site-packages/watson/cli.py", line 441, in <module>
    _SHORTCUT_OPTIONS_VALUES = {`
`  File "/usr/lib/python3.9/site-packages/watson/cli.py", line 442, in <dictcomp>
    k: get_start_time_for_period(k) for k in _SHORTCUT_OPTIONS`
`  File "/usr/lib/python3.9/site-packages/watson/utils.py", line 193, in get_start_time_for_period
    start_time = get_last_full_moon(now)`
`  File "/usr/lib/python3.9/site-packages/watson/fullmoon.py", line 226, in get_last_full_moon
    idx = bisect.bisect_right(fullmoons, now)`
`TypeError: '<' not supported between instances of 'method' and 'int'`
This happened after upgrading python-arrow from 0.17.0 to 1.0.3.  Things get back to normal after downgrading python-arrow to previous version (0.17.0).

**Comment by jmaupetit** [comment] 2021-03-19 08:49
Yes, it has been fixed in #408 but not released yet!

I think it's time for a new release :wink: 

Closing as duplicate of #410

**Closed by jmaupetit** 2021-03-19 08:49 UTC

**Comment by jmaupetit** [comment] 2021-03-19 10:04
:loudspeaker: The new `2.0.0` release including this fix is out! https://pypi.org/project/td-watson/2.0.0/ :fire:
