### ISSUE TITLE
Confused date parsing

### ISSUE THREAD

**Issue by gdetrez** [TailorDev/Watson#100] opened 2016-02-27 09:20 UTC
I noticed the following error with the report command:
```
~ ❯❯❯ watson report -f 2016
Thu 01 January 1970 -> Sat 27 February 2016
```
I looked a bit deeper and here's what I found. The following are parsed correctly:
```
2016-02-14
2016-02
2016.02.14
2016/02/14
2016/02
```

But those appear as Thu 01 January 1970:
```
2016.02
2016
```

Strangely enough, if I add some garbage at the end, it works:
```
$ watson report -f 2016.02foo
Mon 01 February 2016 -> Sat 27 February 2016
...
$ watson report -f 2016foo
Fri 01 January 2016 -> Sat 27 February 2016
...
```

**Comment by gdetrez** [comment] 2016-02-27 09:34
I think I understood it more: if the dates looks like a decimal number, it is intrepreted as a timestamp:
```
~ ❯❯❯ watson report --from $(date --date=2016-01-01 +%s)
Thu 31 December 2015 -> Sat 27 February 2016
```

**Comment by jmaupetit** [comment] 2016-02-27 14:03
Thanks for the report. Should we consider this as a duplicate of #10 ?

**Closed** 2016-09-30 16:18 UTC
Labels: duplicate
