### ISSUE TITLE
watson edit on the currently running frame fails

### ISSUE THREAD

**Issue by cdxOo** [TailorDev/Watson#421] opened 2021-04-06 14:11 UTC
Version 2.0.0

I updated my watson version from 1.10 to 2.0.
In 1.10 I used to be able to call "watson edit" without any argument to edit the currently running frame. In 2.0 I get an error:
```
> watson start foo +mytag
Starting project foo [mytag] at 15:56
> watson edit
Error: Error converting date: Cannot parse argument of type None.
```

I suspect that this might be a bug in 2.0

**Comment by jmaupetit** [comment] 2021-04-06 14:24
Yes it is! But the fix has not been released yet. My bad, sorry :grimacing: 

I'll make a new release this week.

Duplicate of #417

**Closed by jmaupetit** 2021-04-06 14:24 UTC
Labels: bug, duplicate

**Comment by cdxOo** [comment] 2021-04-06 18:23
No problem, its not urgent, at least for me.
I'm sorry I missed the fact that a ticket for this already existed.

**Comment by capelio** [comment] 2021-04-22 23:31
Just checking in @jmaupetit, it doesn't look like a release has been cut for this bug fix. Any ETA on when it'll go out and be available via Homebrew?

**Comment by jmaupetit** [comment] 2021-05-10 13:11
Aaaaand it's published on PyPI, woohoo! https://pypi.org/project/td-watson/2.0.1/

![](https://media3.giphy.com/media/3o7buiQeyYFamzRoR2/giphy.gif)
